export const APPLY_COUPON_REQUEST = 'APPLY_COUPON_REQUEST'
export const APPLY_COUPON_SUCCESS = 'APPLY_COUPON_SUCCESS'
export const APPLY_COUPON_FAILED = 'APPLY_COUPON_FAILED'

export const COUPON_DEACTIVATE_REQUEST = 'COUPON_DEACTIVATE_REQUEST'
export const COUPON_DEACTIVATE_SUCCESS = 'COUPON_DEACTIVATE_SUCCESS'

