export const PRODUCTS_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST'
export const PRODUCTS_LIST_SUCCESS = 'PRODUCTS_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const AUDIO_PRODUCTS_LIST_REQUEST = 'AUDIO_PRODUCTS_LIST_REQUEST'
export const AUDIO_PRODUCTS_LIST_SUCCESS = 'AUDIO_PRODUCTS_LIST_SUCCESS'
export const AUDIO_PRODUCT_LIST_FAIL = 'AUDIO_PRODUCT_LIST_FAIL'

export const COMPUTER_PRODUCTS_LIST_REQUEST = 'COMPUTER_PRODUCTS_LIST_REQUEST'
export const COMPUTER_PRODUCTS_LIST_SUCCESS = 'COMPUTER_PRODUCTS_LIST_SUCCESS'
export const COMPUTER_PRODUCT_LIST_FAIL = 'COMPUTER_PRODUCT_LIST_FAIL'

export const TV_PRODUCTS_LIST_REQUEST = 'TV_PRODUCTS_LIST_REQUEST'
export const TV_PRODUCTS_LIST_SUCCESS = 'TV_PRODUCTS_LIST_SUCCESS'
export const TV_PRODUCT_LIST_FAIL = 'TV_PRODUCT_LIST_FAIL'

export const TRENDING_PRODUCTS_LIST_REQUEST = 'TRENDING_PRODUCTS_LIST_REQUEST'
export const TRENDING_PRODUCTS_LIST_SUCCESS = 'TRENDING_PRODUCTS_LIST_SUCCESS'
export const TRENDING_PRODUCT_LIST_FAIL = 'TRENDING_PRODUCT_LIST_FAIL'




